# Dockerfile.migration
FROM python:3.12-slim

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование кода
COPY . .

# Команда для миграций
CMD ["python", "-m", "alembic", "upgrade", "head"]
